// Code generated by genlambdamux; DO NOT EDIT.
package logtypesapi

import (
	"context"
	"encoding/json"
	"github.com/aws/aws-sdk-go/service/lambda"
	"github.com/aws/aws-sdk-go/service/lambda/lambdaiface"
	"github.com/pkg/errors"
)

type ListAvailableLogTypesOutput = AvailableLogTypes

type LambdaAPIEvent struct {
	ListAvailableLogTypes *struct{}
}

type LambdaClient struct {
	lambdaAPI  lambdaiface.LambdaAPI
	lambdaName string
	validate   func(interface{}) error
}

func NewLambdaClient(lambdaAPI lambdaiface.LambdaAPI, lambdaName string, validate func(interface{}) error) *LambdaClient {
	return &LambdaClient{
		lambdaAPI:  lambdaAPI,
		lambdaName: lambdaName,
		validate:   validate,
	}
}

func (c *LambdaClient) ListAvailableLogTypes(ctx context.Context) (*ListAvailableLogTypesOutput, error) {
	lambdaEvent := LambdaAPIEvent{
		ListAvailableLogTypes: &struct{}{},
	}

	payload, err := json.Marshal(&lambdaEvent)
	if err != nil {
		return nil, err
	}

	lambdaInput := lambda.InvokeInput{
		FunctionName: &c.lambdaName,
		Payload:      payload,
	}

	lambdaOutput, err := c.lambdaAPI.InvokeWithContext(ctx, &lambdaInput)
	if err != nil {
		return nil, err
	}

	if lambdaError := lambdaOutput.FunctionError; lambdaError != nil {
		return nil, errors.New(*lambdaError)
	}

	output := ListAvailableLogTypesOutput{}
	if err := json.Unmarshal(lambdaOutput.Payload, &output); err != nil {
		return nil, err
	}

	return &output, nil
}
