# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Master template for deploying Panther Community

Parameters:
  AccessLogsBucket:
    Type: String
    Description: External bucket for storing S3 access logs. If not specified, the Panther audit bucket is used.
    Default: ''
  AlarmTopicArn:
    Type: String
    Description: An existing SNS topic for CloudWatch alarms. If not specified, one is created for you.
    Default: ''
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  CustomDomain:
    Type: String
    Description: The FQDN that will be used by the web application (defaults to autogenerated ALB URL)
    Default: ''
  Debug:
    Type: String
    Description: Toggle debug logging for all components
    AllowedValues: [true, false]
    Default: false
  EnableS3AccessLogs:
    Type: String
    Description: Enable S3 access logging for all Panther buckets
    AllowedValues: [true, false]
    Default: true
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of LayerVersion ARNs to attach to each Lambda function
    Default: ''
  LogSubscriptionPrincipals:
    Type: CommaDelimitedList
    Description: List of Principal ARNs to allow read access to the ProcessedDataBucket and subscribe access to ProcessedDataTopicArn
    Default: ''
  PythonLayerVersionArn:
    Type: String
    Description: Custom Python layer for analysis and remediation. Defaults to a pre-built layer with 'policyuniverse' and 'requests' pip libraries
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda, API Gateway, and GraphQL
    AllowedValues: ['', Active, PassThrough]
    Default: ''

# TODO: what to use for region and account?
# TODO: can we interpolate the version?

Resources:
  Bootstrap:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:101802775469:applications/panther-community-bootstrap
        SemanticVersion: 1.4.0-alpha
      Parameters:
        AccessLogsBucket: !Ref AccessLogsBucket
        AlarmTopicArn: !Ref AlarmTopicArn
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CustomDomain: !Ref CustomDomain
        Debug: !Ref Debug
        EnableS3AccessLogs: !Ref EnableS3AccessLogs
        LogSubscriptionPrincipals: !Join [',', !Ref LogSubscriptionPrincipals]
        TracingMode: !Ref TracingMode
      Tags:
        Application: Panther
        # SAM will automatically apply the following tags:
        # TODO: does "aws cloudformation deploy" do the same?
        # lambda:createdBy = SAM
        # serverlessrepo:applicationId
        # serverlessrepo:semanticVersion
      TimeoutInMinutes: 20

  BootstrapGateway:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:101802775469:applications/panther-community-bootstrap-gateway
        SemanticVersion: 1.4.0-alpha
      Parameters:
        # If the AlarmTopicArn parameter is blank, Bootstrap will create the topic.
        # That's why this uses the Bootstrap output instead of the parameter.
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn

        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        LayerVersionArns: !Join [',', !Ref LayerVersionArns]
        PythonLayerVersionArn: !Ref PythonLayerVersionArn
        TracingMode: !Ref TracingMode
        UserPoolId: !GetAtt Bootstrap.Outputs.UserPoolId
      Tags:
        Application: Panther
      TimeoutInMinutes: 20

Outputs:
  GraphQlUrl:
    Description: The URL for the AppSync GraphQL endpoint
    Value: !GetAtt Bootstrap.Outputs.GraphQLApiEndpoint
  LoadBalancerUrl:
    Description: Panther URL - application load balancer or custom domain
    Value: !GetAtt Bootstrap.Outputs.LoadBalancerUrl
