# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: Master template for deploying Panther Community

Parameters:
  # FirstUserEmail is the only required parameter

  # Alphabetize parameters so it's easy to compare side-by-side with other code that passes values
  # and because the CloudFormation console always shows parameters in alphabetical order.
  AccessLogsBucketName:
    Type: String
    Description: Name of the S3 bucket for storing S3 access logs (has no effect if EnableS3AccessLogs=false). Defaults to the Panther audit bucket, created automatically.
    Default: ''
    AllowedPattern: '^([a-z0-9.-]{3,63})?$'
  AlarmTopicArn:
    Type: String
    Description: SNS topic notified by CloudWatch alarms. If not specified, a topic is created for you.
    Default: ''
    # Example: "arn:aws:sns:us-west-2:111122223333:panther-cw-alarms"
    AllowedPattern: '^(arn:(aws|aws-cn|aws-us-gov):sns:[a-z]{2}-[a-z]{4,9}-[1-9]:\d{12}:\S+)?$'
  CertificateArn:
    Type: String
    Description: TLS certificate (ACM or IAM) used by the web app - see also CustomDomain. If not specified, a self-signed cert is created for you.
    Default: ''
    # Example: "arn:aws:acm:us-west-2:111122223333:certificate/6e51b91b-0d7d-4592-89a3-c113c78e3ab3" or
    # "arn:aws:iam::111122223333:server-certificate/panther/us-west-2/MyCert"
    AllowedPattern: '^((arn:(aws|aws-cn|aws-us-gov):acm:[a-z]{2}-[a-z]{4,9}-[1-9]:\d{12}:certificate\/[a-f0-9-]{36})|(arn:(aws|aws-cn|aws-us-gov):iam::\d{12}:server-certificate\/\S+))?$'
  CloudWatchLogRetentionDays:
    Type: Number
    Description: Number of days to retain CloudWatch logs (e.g. Lambda execution logs)
    Default: 365
    MinValue: 1
  CompanyDisplayName:
    Type: String
    Description: Company name displayed in Settings > General
    Default: AwesomeCo
    MinLength: 1
  CustomDomain:
    Type: String
    Description: If CertificateArn is registered for a custom domain (e.g. 'app.example.com'), list that here.
    Default: ''
    AllowedPattern: '^([a-z0-9.-]+\.[a-z]{2,})?$'
  DataReplicationBucketName:
    Type: String
    Description: Replicate processed log data to this S3 bucket for Glacier backup storage
    Default: ''
    AllowedPattern: '^(arn:(aws|aws-cn|aws-us-gov):s3:::[a-z0-9.-]{3,63})?$'
  Debug:
    Type: String
    Description: Toggle debug logging for all components
    AllowedValues: [true, false]
    Default: false
  EnableCloudTrail:
    Type: String
    Description: Create a CloudTrail in this account configured for log processing. Has no effect if OnboardSelf=false
    AllowedValues: [true, false]
    Default: false
  EnableGuardDuty:
    Type: String
    Description: Enable GuardDuty in this account configured for log processing. Has no effect if OnboardSelf=false
    AllowedValues: [true, false]
    Default: false
  EnableS3AccessLogs:
    Type: String
    Description: Enable S3 access logging for all Panther buckets. This is strongly recommended for security, but comes at an additional cost.
    AllowedValues: [true, false]
    Default: true
  FirstUserEmail:
    Type: String
    Description: Initial Panther user - email address
    # There is no perfect email regex, but this is good enough 99% of the time.
    # https://www.regular-expressions.info/email.html
    #
    # The goal is to fail early if the user provides an invalid email, otherwise the deploy will
    # fail at the very last step (onboarding the first user in the web stack), and the entire thing
    # will rollback.
    AllowedPattern: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  FirstUserFamilyName:
    Type: String
    Description: Initial Panther user - last name
    Default: Community
    MinLength: 1
  FirstUserGivenName:
    Type: String
    Description: Initial Panther user - first name
    Default: PantherUser
    MinLength: 1
  ImageRegistry:
    Type: String
    Description: Docker image registry which stores web app images. Used only when deploying from source and otherwise defaults to the Panther public account.
    Default: ''
  InitialAnalysisPackUrls:
    Type: CommaDelimitedList
    Description: Comma-separated list of Python analysis pack URLs installed on the first deployment
    Default: https://github.com/panther-labs/panther-analysis/releases/latest/download/panther-analysis-all.zip
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: Comma-separated list of at most 3 LayerVersion ARNs to attach to each Lambda function (e.g. if you have a serverless monitoring service)
    Default: ''
  LoadBalancerSecurityGroupCidr:
    Type: String
    Description: Allow HTTP(S) ingress access to the web app (ALB) security group from this IP block. Use 0.0.0.0/0 to allow unrestricted access
    Default: 0.0.0.0/0
    # cfn-lint suggested this regex pattern:
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
  LogProcessorLambdaMemorySize:
    Type: Number
    Description: Log processor Lambda memory allocation. Increase to eliminate out-of-memory errors or reduce processing time (in exchange for higher cost)
    MinValue: 256 # 128 is too small, risks OOM errors
    MaxValue: 3008
    Default: 1024
  LogSubscriptionPrincipals:
    Type: CommaDelimitedList
    Description: Comma-separated list of AWS principal ARNs which will be authorized to subscribe to processed log data S3 notifications
    Default: ''
  OnboardSelf:
    Type: String
    Description: Configure Panther to automatically onboard itself as a data source
    AllowedValues: [true, false]
    Default: true
  PythonLayerVersionArn:
    Type: String
    Description: Custom Python layer for analysis and remediation. Defaults to a pre-built layer with 'policyuniverse' and 'requests' pip libraries
    Default: ''
    # Example: "arn:aws:lambda:us-west-2:111122223333:layer:panther-analysis:143"
    AllowedPattern: '^(arn:(aws|aws-cn|aws-us-gov):lambda:[a-z]{2}-[a-z]{4,9}-[1-9]:\d{12}:layer:\S+:\d+)?$'
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda, API Gateway, and GraphQL
    AllowedValues: ['', Active, PassThrough]
    Default: ''

Mappings:
  Constants:
    Panther:
      Version: 1.8.0-beta

Conditions:
  RegistryProvided: !Not [!Equals [!Ref ImageRegistry, '']]
  OnboardSelf: !Equals [!Ref OnboardSelf, true]

Resources:
  Bootstrap:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: bootstrap.yml
      Parameters:
        AccessLogsBucket: !Ref AccessLogsBucketName
        AlarmTopicArn: !Ref AlarmTopicArn
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CustomDomain: !Ref CustomDomain
        DataReplicationBucket: !Ref DataReplicationBucketName
        Debug: !Ref Debug
        DeployFromSource: false
        EnableS3AccessLogs: !Ref EnableS3AccessLogs
        LoadBalancerSecurityGroupCidr: !Ref LoadBalancerSecurityGroupCidr
        LogSubscriptionPrincipals: !Join [',', !Ref LogSubscriptionPrincipals]
        TracingMode: !Ref TracingMode
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-bootstrap # friendly name, not actual stack name

  BootstrapGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/embedded.bootstrap_gateway.yml # generated by 'mage build:cfn'
      Parameters:
        # If the AlarmTopicArn parameter is blank, Bootstrap will create the topic.
        # That's why this uses the Bootstrap output instead of the parameter.
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AthenaResultsBucket: !GetAtt Bootstrap.Outputs.AthenaResultsBucket
        AuditLogsBucket: !GetAtt Bootstrap.Outputs.AuditLogsBucket
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CompanyDisplayName: !Ref CompanyDisplayName
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        ImageRegistryName: !GetAtt Bootstrap.Outputs.ImageRegistryName
        LayerVersionArns: !Join [',', !Ref LayerVersionArns]
        ProcessedDataBucket: !GetAtt Bootstrap.Outputs.ProcessedDataBucket
        PythonLayerVersionArn: !Ref PythonLayerVersionArn
        TracingMode: !Ref TracingMode
        UserPoolId: !GetAtt Bootstrap.Outputs.UserPoolId
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-bootstrap-gateway

  Appsync:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: appsync.yml
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AnalysisApi: !Sub https://${BootstrapGateway.Outputs.AnalysisApiEndpoint}
        ApiId: !GetAtt Bootstrap.Outputs.GraphQLApiId
        ComplianceApi: !Sub https://${BootstrapGateway.Outputs.ComplianceApiEndpoint}
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        RemediationApi: !Sub https://${BootstrapGateway.Outputs.RemediationApiEndpoint}
        ResourcesApi: !Sub https://${BootstrapGateway.Outputs.ResourcesApiEndpoint}
        ServiceRole: !GetAtt Bootstrap.Outputs.AppsyncServiceRoleArn
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-appsync

  CloudSecurity:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cloud_security.yml
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AnalysisApiId: !GetAtt BootstrapGateway.Outputs.AnalysisApiId
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        ComplianceApiId: !GetAtt BootstrapGateway.Outputs.ComplianceApiId
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        Debug: !Ref Debug
        LayerVersionArns: !Join [',', !Ref LayerVersionArns]
        ProcessedDataBucket: !GetAtt Bootstrap.Outputs.ProcessedDataBucket
        ProcessedDataTopicArn: !GetAtt Bootstrap.Outputs.ProcessedDataTopicArn
        PythonLayerVersionArn: !GetAtt BootstrapGateway.Outputs.PythonLayerVersionArn
        RemediationApiId: !GetAtt BootstrapGateway.Outputs.RemediationApiId
        ResourcesApiId: !GetAtt BootstrapGateway.Outputs.ResourcesApiId
        SqsKeyId: !GetAtt Bootstrap.Outputs.QueueEncryptionKeyId
        TracingMode: !Ref TracingMode
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-cloud-security

  Core:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: core.yml
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AnalysisApiId: !GetAtt BootstrapGateway.Outputs.AnalysisApiId
        AnalysisVersionsBucket: !GetAtt Bootstrap.Outputs.AnalysisVersionsBucket
        AppDomainURL: !GetAtt Bootstrap.Outputs.LoadBalancerUrl
        AthenaResultsBucket: !GetAtt Bootstrap.Outputs.AthenaResultsBucket
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CompanyDisplayName: !Ref CompanyDisplayName
        CompanyEmail: !Ref FirstUserEmail
        ComplianceApiId: !GetAtt BootstrapGateway.Outputs.ComplianceApiId
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        Debug: !Ref Debug
        DynamoScalingRoleArn: !GetAtt Bootstrap.Outputs.DynamoScalingRoleArn
        InputDataBucket: !GetAtt Bootstrap.Outputs.InputDataBucket
        InputDataTopicArn: !GetAtt Bootstrap.Outputs.InputDataTopicArn
        LayerVersionArns: !Join [',', !Ref LayerVersionArns]
        OutputsKeyId: !GetAtt Bootstrap.Outputs.OutputsEncryptionKeyId
        ProcessedDataBucket: !GetAtt Bootstrap.Outputs.ProcessedDataBucket
        SqsKeyId: !GetAtt Bootstrap.Outputs.QueueEncryptionKeyId
        TracingMode: !Ref TracingMode
        UserPoolId: !GetAtt Bootstrap.Outputs.UserPoolId
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-core

  Dashboards:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: dashboards.yml
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-cw-dashboards

  LogAnalysis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_analysis.yml
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AnalysisApiId: !GetAtt BootstrapGateway.Outputs.AnalysisApiId
        AthenaResultsBucket: !GetAtt Bootstrap.Outputs.AthenaResultsBucket
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        Debug: !Ref Debug
        InputDataBucket: !GetAtt Bootstrap.Outputs.InputDataBucket
        InputDataTopicArn: !GetAtt Bootstrap.Outputs.InputDataTopicArn
        LayerVersionArns: !Join [',', !Ref LayerVersionArns]
        LogProcessorLambdaMemorySize: !Ref LogProcessorLambdaMemorySize
        ProcessedDataBucket: !GetAtt Bootstrap.Outputs.ProcessedDataBucket
        ProcessedDataTopicArn: !GetAtt Bootstrap.Outputs.ProcessedDataTopicArn
        PythonLayerVersionArn: !GetAtt BootstrapGateway.Outputs.PythonLayerVersionArn
        SqsKeyId: !GetAtt Bootstrap.Outputs.QueueEncryptionKeyId
        TablesSignature: !FindInMap [Constants, Panther, Version] # this changes with version, forcing table schema updates
        TracingMode: !Ref TracingMode
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-log-analysis

  Onboard:
    Condition: OnboardSelf
    # Onboard stack adds new source integrations, which requires custom resources (bootstrap-gateway),
    # source-api (core), and queues from cloud-security and log-analysis to exist.
    DependsOn: [BootstrapGateway, CloudSecurity, Core, LogAnalysis]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: onboard.yml
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AuditLogsBucket: !GetAtt Bootstrap.Outputs.AuditLogsBucket
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        EnableCloudTrail: !Ref EnableCloudTrail
        EnableGuardDuty: !Ref EnableGuardDuty
        EnableS3AccessLogs: !Ref EnableS3AccessLogs
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-onboard

  Web:
    Type: AWS::CloudFormation::Stack
    # Custom resources in this stack require the analysis-api, users-api, and both Python engines to exist
    DependsOn: [CloudSecurity, Core, LogAnalysis]
    Properties:
      TemplateURL: web_server.yml
      TimeoutInMinutes: 20 # if something goes wrong, the ECS service will get stuck in a retry loop for 4 hours
      Parameters:
        AlarmTopicArn: !GetAtt Bootstrap.Outputs.AlarmTopicArn
        AnalysisApiEndpoint: !GetAtt BootstrapGateway.Outputs.AnalysisApiEndpoint
        AppClientId: !GetAtt BootstrapGateway.Outputs.AppClientId
        CertificateArn: !Ref CertificateArn
        CloudWatchLogRetentionDays: !Ref CloudWatchLogRetentionDays
        CustomResourceVersion: !FindInMap [Constants, Panther, Version]
        ElbArn: !GetAtt Bootstrap.Outputs.LoadBalancerArn
        ElbFullName: !GetAtt Bootstrap.Outputs.LoadBalancerFullName
        ElbTargetGroup: !GetAtt Bootstrap.Outputs.LoadBalancerTargetGroup
        FirstUserEmail: !Ref FirstUserEmail
        FirstUserFamilyName: !Ref FirstUserFamilyName
        FirstUserGivenName: !Ref FirstUserGivenName
        GraphQLApiEndpoint: !GetAtt Bootstrap.Outputs.GraphQLApiEndpoint
        Image: !Sub
          - '${registry}:${tag}'
          - registry: !If
              - RegistryProvided
              - !Ref ImageRegistry
              - !Sub 349240696275.dkr.ecr.${AWS::Region}.amazonaws.com/panther-community
            tag: !FindInMap [Constants, Panther, Version]
        InitialAnalysisPackUrls: !Join [',', !Ref InitialAnalysisPackUrls]
        PantherVersion: !Sub
          - v${version} # has to be prefixed with 'v' for docs link in web app to work
          - version: !FindInMap [Constants, Panther, Version]
        SecurityGroup: !GetAtt Bootstrap.Outputs.WebSecurityGroup
        SubnetOneId: !GetAtt Bootstrap.Outputs.SubnetOneId
        SubnetTwoId: !GetAtt Bootstrap.Outputs.SubnetTwoId
        UserPoolId: !GetAtt Bootstrap.Outputs.UserPoolId
      Tags:
        - Key: Application
          Value: Panther
        - Key: PantherEdition
          Value: Community
        - Key: PantherVersion
          Value: !FindInMap [Constants, Panther, Version]
        - Key: Stack
          Value: panther-web

Outputs:
  LoadBalancerUrl:
    Description: Panther URL serving the web app
    Value: !Sub https://${Bootstrap.Outputs.LoadBalancerUrl}
