# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: Template for Panther monitoring related resources (e.g., metrics, alarms and dashboards)

Parameters:
  AppsyncId:
    Type: String
    Description: Appsync GraphQL ID
  LoadBalancerFullName:
    Type: String
    Description: Full name of the application load balancer

  AlarmTopicArn:
    Type: String
    Description: An existing SNS topic for CloudWatch alarms. If not specified, one is created for you.
    Default: ''

Conditions:
  CreateAlarmSNSTopic: !Equals [!Ref AlarmTopicArn, '']

Resources:
  # All of these nested stacks are autogenerated with mage build:cfn
  Dashboards:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/monitoring/dashboards.json

  Metrics:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/monitoring/metrics.json

  # Alarms
  AlarmNotifications:
    Condition: CreateAlarmSNSTopic
    Type: AWS::SNS::Topic
    Properties:
      TopicName: panther-alarms

  ComplianceAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AlarmTopicArn: !If [CreateAlarmSNSTopic, !Ref AlarmNotifications, !Ref AlarmTopicArn]
      TemplateURL: ../out/deployments/monitoring/compliance_alarms.json

  CoreAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AlarmTopicArn: !If [CreateAlarmSNSTopic, !Ref AlarmNotifications, !Ref AlarmTopicArn]
        AppsyncId: !Ref AppsyncId
      TemplateURL: ../out/deployments/monitoring/core_alarms.json

  LogAnalysisAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AlarmTopicArn: !If [CreateAlarmSNSTopic, !Ref AlarmNotifications, !Ref AlarmTopicArn]
      TemplateURL: ../out/deployments/monitoring/log_analysis_alarms.json

  WebAlarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AlarmTopicArn: !If [CreateAlarmSNSTopic, !Ref AlarmNotifications, !Ref AlarmTopicArn]
        LoadBalancerFullName: !Ref LoadBalancerFullName
      TemplateURL: ../out/deployments/monitoring/web_alarms.json
