# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: Template for Panther monitoring related resources (e.g., metrics, alarms and dashboards)

Resources:
  ##### Nested Stacks: CloudWatch #####
  Dashboards:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/cloudwatch/dashboards.json

  Metrics:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/cloudwatch/metrics.json

  Alarms:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../out/deployments/cloudwatch/alarms.json
