# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: Template for onboarding the Panther account into Panther itself

Parameters:
  CreateRoles:
    Type: String
    Description: If "true", then create roles
    AllowedValues: ['true', 'false']

Conditions:
  CreateRoles: !Equals [!Ref CreateRoles, 'true']

Resources:
  # Permissions for CloudSecurity to scan this Account
  ComplianceRoles:
    Condition: CreateRoles
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        MasterAccountId: !Ref AWS::AccountId
        DeployRemediation: 'true'
        DeployCloudWatchEventSetup: 'true'
      TemplateURL: auxiliary/cloudformation/panther-compliance-iam.yml

  StackSetAdminRole:
    Condition: CreateRoles
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: auxiliary/cloudformation/panther-stackset-iam-admin-role.yml

  # Configure SNS Topic to receive bucket notifications
  # This topic is used to notify the log processor queue whenever new data is written to the auditing bucket.
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: panther-auditlog-processing
      # <cfndoc>
      # The panther-auditlog-processing topic is used to send s3 notifications to log processing
      # for log sources internal to the Panther account.
      #</cfndoc>

  # This policy is used to allow S3 to publish to the topic when new data is written to S3
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Reference: https://amzn.to/2ouFmhK
          - Sid: AllowS3EventNotifications
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
          - Sid: AllowCloudTrailNotification
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sns:Publish
            Resource: !Ref Topic
          - Sid: AllowSubscriptionToPanther
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: sns:Subscribe
            Resource: !Ref Topic
      Topics:
        - !Ref Topic

  # SNS Topic subscription to Panther
  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:panther-input-data-notifications-queue
      Protocol: sqs
      RawMessageDelivery: false
      TopicArn: !Ref Topic

Outputs:
  LogProcessingTopicArn:
    Description: The ARN of the SNS Topic that will be notifying Panther of new data.
    Value: !Ref Topic
