version: 2.1

# The images that jobs can have
executors:
  panther-buildpack:
    docker:
      - image: pantherlabs/panther-buildpack:1.1.2

# The pool of jobs that that our CI will be able to run
jobs:
  mage_test_ci:
    executor: panther-buildpack
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mage setup # TODO: cache these
      - run:
          name: Run all tests
          command: mage test:ci

  npm_audit:
    executor: panther-buildpack
    steps:
      - checkout
      - run:
          name: Audit NPM packages
          command: npm audit # does not require installing packages first

workflows:
  version: 2
  pipeline:
    jobs:
      - mage_test_ci
      - npm_audit
