version: 2.1

# The images that jobs can have
executors:
  panther-buildpack:
    docker:
      - image: pantherlabs/panther-buildpack:1.8.0

# Commands which are re-used across multiple jobs
commands:
  restore_bin_cache:
    steps:
      - restore_cache:
          name: 'Restore cache: .setup binaries'
          keys:
            - setup8-{{ checksum "tools/mage/setup/setup.go" }}

  restore_go_cache:
    steps:
      - restore_cache:
          name: 'Restore cache: go modules'
          keys:
            - gomod8-{{ checksum "go.mod" }}

  restore_npm_cache:
    steps:
      - restore_cache:
          name: 'Restore cache: npm'
          keys:
            - npm8-{{ checksum "package-lock.json" }}

  restore_pip_cache:
    steps:
      - restore_cache:
          name: 'Restore cache: python env'
          keys:
            - venv8-{{ checksum "requirements.txt" }}

jobs:
  setup:
    # Install dependencies and compile the mage binary.
    # Subsequent jobs can load libraries from the cache and mage from workspace storage.
    executor: panther-buildpack
    resource_class: large
    steps:
      - checkout
      - restore_bin_cache
      - restore_go_cache
      - restore_npm_cache
      - restore_pip_cache
      - run:
          # This is the only time 'mage' is invoked directly in CI
          name: Compile mage binary
          command: mage -compile /tmp/panther/magebin
      - run:
          # "mage setup" will have no effect unless new dependencies have been introduced.
          name: Install new dependencies
          command: /tmp/panther/magebin setup
      - run:
          name: Debugging
          command: |
            ls .setup
            ls .setup/venv/bin
      - persist_to_workspace:
          root: /tmp/panther
          paths:
            - magebin
      - save_cache:
          name: 'Save cache: .setup binaries'
          key: setup8-{{ checksum "tools/mage/setup/setup.go" }}
          paths:
            - .setup/golangci-lint
            - .setup/swagger
            - .setup/terraform
      - save_cache:
          name: 'Save cache: go modules'
          key: gomod8-{{ checksum "go.mod" }}
          paths:
            - /go/bin/goimports
            - /go/pkg/mod
      - save_cache:
          name: 'Save cache: npm'
          key: npm8-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          name: 'Save cache: python env'
          key: venv8-{{ checksum "requirements.txt" }}
          paths:
            - .setup/venv

  generate_and_fmt:
    # Runs 'mage build:api build:cfn fmt' and commits any resulting changes.
    #
    # If there are changes committed, CircleCI will automatically stop the remaining jobs
    # and restart the entire workflow with the new commit.
    executor: panther-buildpack
    resource_class: large
    steps:
      - attach_workspace:
          at: /tmp/panther
      - checkout
      - restore_bin_cache # swagger (build:api) and terraform (fmt)
      - restore_go_cache # goimports (fmt)
      - restore_npm_cache # prettier (fmt)
      - restore_pip_cache # yapf (fmt)
      - run:
          name: Generate and format source files
          command: /tmp/panther/magebin build:api build:cfn fmt
      - run:
          name: Push changes (if any) to remote ref
          command: |
            git config --global user.email "github-service-account@runpanther.io"
            git config --global user.name "panther-bot"
            git add -A .
            git commit -m "mage build:api build:cfn fmt" || true
            git push origin $CIRCLE_BRANCH

  test_cfn:
    executor: panther-buildpack
    steps:
      - attach_workspace:
          at: /tmp/panther
      - checkout
      - restore_bin_cache # Terraform
      - restore_pip_cache # cfn-lint
      - run:
          name: mage test:cfn
          command: /tmp/panther/magebin test:cfn

  test_go:
    executor: panther-buildpack
    resource_class: large
    steps:
      - attach_workspace:
          at: /tmp/panther
      - checkout
      - restore_bin_cache # golangci-lint
      - restore_go_cache
      - restore_pip_cache # cfn-flip
      - run:
          name: mage test:go
          command: /tmp/panther/magebin test:go

  test_python:
    executor: panther-buildpack
    steps:
      - attach_workspace:
          at: /tmp/panther
      - checkout
      - restore_pip_cache
      - run:
          name: mage test:python
          command: /tmp/panther/magebin test:python

  test_web:
    executor: panther-buildpack
    resource_class: large
    steps:
      - attach_workspace:
          at: /tmp/panther
      - checkout
      - restore_npm_cache
      - run:
          name: mage test:web
          command: /tmp/panther/magebin test:web

  npm_audit:
    executor: panther-buildpack
    resource_class: small
    steps:
      - checkout
      - run:
          name: Audit NPM packages
          command: npm audit --production # does not require installing packages first

  bundlesize:
    executor: panther-buildpack
    steps:
      - checkout
      - restore_npm_cache
      - run:
          name: Check bundle size
          command: npm run bundlesize

  # Upload dependency metadata to FOSSA, analyze offline
  fossa_upload:
    executor: panther-buildpack
    resource_class: small
    steps:
      - checkout
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          command: fossa # generate config file, run dependency analysis, and upload metadata to FOSSA

workflows:
  version: 2
  pipeline:
    jobs:
      - npm_audit
      - setup
      - generate_and_fmt:
          filters:
            branches:
              ignore: master
          requires:
            - setup
      - test_cfn:
          requires:
            - setup
      - test_go:
          requires:
            - setup
      - test_python:
          requires:
            - setup
      - test_web:
          requires:
            - setup
      - bundlesize:
          requires:
            - setup
      - fossa_upload:
          filters:
            branches:
              only: master
