# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deploys the IAM role that allows Panther to remediate resources in an account
Metadata:
  Version: 1.0

Parameters:
  MasterAccountId:
    Type: String
    Description: The account ID where Panther is deployed in

Resources:
  RemediationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PantherRemediationRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${MasterAccountId}:root
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:SecureTransport: true
      Policies:
        - PolicyName: UpdateCloudTrail
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudtrail:CreateTrail
                  - cloudtrail:StartLogging
                  - cloudtrail:UpdateTrail
                Resource: '*'
        - PolicyName: UpdateDDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:UpdateTable
                Resource: '*'
        - PolicyName: UpdateEC2
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateFlowLogs
                  - ec2:StopInstances
                  - ec2:TerminateInstances
                Resource: '*'
        - PolicyName: UpdateGuardDuty
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - guardduty:CreateDetector
                Resource: '*'
        - PolicyName: UpdateIAM
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateAccessKey
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteAccessKey
                  - iam:UpdateAccessKey
                  - iam:UpdateAccountPasswordPolicy
                Resource: '*'
        - PolicyName: UpdateKMS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:EnableKeyRotation
                Resource: '*'
        - PolicyName: UpdateRDS
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - rds:ModifyDBInstance
                  - rds:ModifyDBSnapshotAttribute
                Resource: '*'
        - PolicyName: UpdateLogging
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                Resource: '*'
        - PolicyName: UpdateS3
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketVersioning
                  - s3:PutBucketLogging
                  - s3:PutBucketAcl
                  - s3:PutEncryptionConfiguration
                  - s3:PutBucketPublicAccessBlock
                Resource: '*'
