# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# TODO Add KMS encryption option for S3 Bucket
AWSTemplateFormatVersion: 2010-09-09
Description: Panther Rules Engine Customer Account Cross Account Read-only S3 and Secrets Role
Parameters:
  PantherMasterAccountID:
    Type: String
    Description: Enter the 12 Digit AWS Panther Master AccountID located in Panther under General > Settings.
  PantherRulesEngineRoleName:
    Type: String
    Description: Enter the name of the Panther Rules Engine Role name which can be found in the AWS Console under IAM by searching "rules" in the Panther Master Account.
  SecretName:
    Type: String
    Default: NoSecret
    Description: Enter the name of the Secret in Secrets Manger that will be accessible from the Panther Rules Engine.
  TargetBucketName:
    Type: String
    Description: Enter the S3 Bucket that the Panther Rules Engine can Read from.

Resources:
  PantherRulesEngineIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub arn:aws:iam::${PantherMasterAccountID}:role/${PantherRulesEngineRoleName}

      Policies:
        - PolicyName: panther-rule-engine-cross-account-read-only-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !Sub arn:aws:s3:::${TargetBucketName}
                  - !Sub arn:aws:s3:::${TargetBucketName}/*
              - Effect: Allow
                Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretName}

      RoleName: !Sub PantherRulesEngineCrossAccountReadOnlyRole-${AWS::Region}

Outputs:
  PantherRulesEngineCrossAccountIamRoleName:
    Description: Panther Rules Engine Read-only IAM Role Name
    Value: !Ref PantherRulesEngineIamRole
  PantherRulesEngineCrossAccountIamRoleARN:
    Description: Panther Rules Engine Read-only IAM Role ARN
    Value: !GetAtt PantherRulesEngineIamRole.Arn
