# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for deploying Panther

Metadata:
  Version: v1.1.2

Resources:
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PantherDeploymentRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:SecureTransport: true
      Description: IAM role for deploying Panther
      Tags:
        - Key: Application
          Value: Panther

  DeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PantherDeployment
      Roles:
        - !Ref DeploymentRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: # permissions which can't be restricted to specific resources
              - acm:*
              - apigateway:*
              - appsync:*
              - athena:*
              - cloudformation:Describe*
              - cloudformation:List*
              - cloudtrail:DescribeTrails
              - cloudtrail:CreateTrail
              - cloudwatch:*
              - cognito-idp:*
              - dynamodb:List*
              - ec2:AssociateRouteTable
              - ec2:AssociateSubnetCidrBlock
              - ec2:AssociateVpcCidrBlock
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AttachInternetGateway
              - ec2:CreateFlowLogs
              - ec2:CreateInternetGateway
              - ec2:CreateRoute
              - ec2:CreateRouteTable
              - ec2:CreateSecurityGroup
              - ec2:CreateSubnet
              - ec2:CreateTags
              - ec2:CreateVpc
              - ec2:DeleteFlowLogs
              - ec2:DeleteInternetGateway
              - ec2:DeleteRoute
              - ec2:DeleteRouteTable
              - ec2:DeleteSecurityGroup
              - ec2:DeleteSubnet
              - ec2:DeleteTags
              - ec2:DeleteVpc
              - ec2:Describe*
              - ec2:DetachInternetGateway
              - ec2:DisassociateRouteTable
              - ec2:DisassociateSubnetCidrBlock
              - ec2:ModifySubnetAttribute
              - ec2:ModifyVpcAttribute
              - ec2:ReplaceRoute
              - ec2:ReplaceRouteTableAssociation
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:UpdateSecurityGroupRuleDescriptionsEgress
              - ec2:UpdateSecurityGroupRuleDescriptionsIngress
              - elasticloadbalancing:*
              - ecr:GetAuthorizationToken
              - ecs:*
              - events:*
              - glue:*
              - guardduty:CreatePublishingDestination
              - guardduty:ListDetectors
              - kms:CreateKey
              - kms:List*
              - lambda:*EventSourceMapping
              - lambda:List*
              - logs:*
              - sns:List*
              - sqs:List*
              - states:CreateStateMachine
              - states:TagResource
              - states:UntagResource
            Resource: '*'
          - Effect: Allow
            Action: # permissions for handling self-onboarding CloudTrail
              - cloudtrail:AddTags
              - cloudtrail:DeleteTrail
              - cloudtrail:PutEventSelectors
              - cloudtrail:StartLogging
              - cloudtrail:StopLogging
              - cloudtrail:UpdateTrail
            Resource: !Sub arn:${AWS::Partition}:cloudtrail:*:${AWS::AccountId}:trail/panther-cloudtrail-*
          - Effect: Allow
            Action: cloudformation:*
            Resource:
              - !Sub arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stack/panther-*
              - !Sub arn:${AWS::Partition}:cloudformation:*:${AWS::AccountId}:stackset/panther-*
              - !Sub arn:${AWS::Partition}:cloudformation:*:aws:transform/Serverless-2016-10-31
          - Effect: Allow
            Action: dynamodb:*
            Resource: !Sub arn:${AWS::Partition}:dynamodb:*:${AWS::AccountId}:table/panther-*
          - Effect: Allow
            Action: ecr:*
            Resource: !Sub arn:${AWS::Partition}:ecr:*:${AWS::AccountId}:repository/panther-*
          - Effect: Allow
            Action: execute-api:Invoke
            Resource: !Sub arn:${AWS::Partition}:execute-api:*:${AWS::AccountId}:*
          - Effect: Allow
            Action: iam:*
            Resource:
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/AWSServiceRole*
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/*
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/panther-*
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/Panther*
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:server-certificate/panther/*
          - Effect: Allow
            Action: kms:*
            Resource:
              - !Sub arn:${AWS::Partition}:kms:*:${AWS::AccountId}:alias/panther-*
              - !Sub arn:${AWS::Partition}:kms:*:${AWS::AccountId}:key/*
          - Effect: Allow
            Action: lambda:*
            Resource:
              - !Sub arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:event-source-mapping:*
              - !Sub arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:function:panther-*
              - !Sub arn:${AWS::Partition}:lambda:*:${AWS::AccountId}:layer:panther-*
          - Effect: Allow
            Action: s3:*
            Resource: !Sub arn:${AWS::Partition}:s3:::panther-*
          - Effect: Allow
            Action: sns:*
            Resource: !Sub arn:${AWS::Partition}:sns:*:${AWS::AccountId}:panther-*
          - Effect: Allow
            Action: sqs:*
            Resource: !Sub arn:${AWS::Partition}:sqs:*:${AWS::AccountId}:panther-*
          - Effect: Allow
            Action: states:*
            Resource:
              - !Sub arn:${AWS::Partition}:states:*:${AWS::AccountId}:activity:panther-*
              - !Sub arn:${AWS::Partition}:states:*:${AWS::AccountId}:execution:panther-*:*
              - !Sub arn:${AWS::Partition}:states:*:${AWS::AccountId}:stateMachine:panther-*
