# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deploys the latest Panther Remediation Lambda from SAR and creates the appropriate IAM role to allow invocation of Lambda from Panther
Metadata:
  Version: 1.1

Parameters:
  MasterAccountId:
    Type: String
    Description:  AWS account ID of the account running the Panther backend

Resources:
  PantherLambdaInvocationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PantherLambdaInvocationRole
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${MasterAccountId}:root
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:SecureTransport: true
      Policies:
        - PolicyName: AllowInvocation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt PantherAWSRemediations.Outputs.LambdaArn

  PantherAWSRemediations:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:349240696275:applications/aws-remediations
        SemanticVersion: 0.1.2
      Parameters:
        IsMasterAccount: 'true'
        CreateSSMDocument: 'false'
        LambdaLoggingLevel: 'INFO'
        LambdaLogsRetentionDays: '365'

Outputs:
  LambdaArn:
    Description: The ARN of the Lambda function that will perform the remediative actions.
    Value: !GetAtt PantherAWSRemediations.Outputs.LambdaArn
