# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for deploying Panther

Metadata:
  Version: v1.0.0

Resources:
  AuditRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PantherDeploymentRole
      Description: IAM role for deploying Panther
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/SecurityAudit
      Policies:
        - PolicyName: CloudFormation
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DetectStackDrift
                  - cloudformation:DetectStackResourceDrift
                Resource: '*'
      Tags:
        - Key: Application
          Value: Panther

#  {
#    "Version": "2012-10-17",
#    "Statement": [
#    {
#      "Effect": "Allow",
#      "Action": "cloudformation:*",
#      "Resource": [
#        "arn:aws:cloudformation:us-east-1:101802775469:stack/panther-*",
#        "arn:aws:cloudformation:us-east-1:aws:transform/Serverless-2016-10-31"
#      ]
#    },
#    {
#      "Effect": "Allow",
#      "Action": "dynamodb:*",
#      "Resource": "arn:aws:dynamodb:us-east-1:101802775469:table/panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": [
#        "ec2:AssociateRouteTable",
#        "ec2:AssociateSubnetCidrBlock",
#        "ec2:AssociateVpcCidrBlock",
#        "ec2:AuthorizeSecurityGroupEgress",
#        "ec2:AuthorizeSecurityGroupIngress",
#        "ec2:AttachInternetGateway",
#        "ec2:CreateInternetGateway",
#        "ec2:CreateRoute",
#        "ec2:CreateRouteTable",
#        "ec2:CreateSecurityGroup",
#        "ec2:CreateSubnet",
#        "ec2:CreateTags",
#        "ec2:CreateVpc",
#        "ec2:DeleteInternetGateway",
#        "ec2:DeleteRoute",
#        "ec2:DeleteRouteTable",
#        "ec2:DeleteSecurityGroup",
#        "ec2:DeleteSubnet",
#        "ec2:DeleteTags",
#        "ec2:DeleteVpc",
#        "ec2:Describe*",
#        "ec2:DetachInternetGateway",
#        "ec2:DisassociateRouteTable",
#        "ec2:DisassociateSubnetCidrBlock",
#        "ec2:ModifySubnetAttribute",
#        "ec2:ModifyVpcAttribute",
#        "ec2:ReplaceRoute",
#        "ec2:ReplaceRouteTableAssociation",
#        "ec2:RevokeSecurityGroupEgress",
#        "ec2:RevokeSecurityGroupIngress",
#        "ec2:UpdateSecurityGroupRuleDescriptionsEgress",
#        "ec2:UpdateSecurityGroupRuleDescriptionsIngress",
#        "elasticloadbalancing:*"
#      ],
#      "Resource": "*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "ecr:*",
#      "Resource": "arn:aws:ecr:us-east-1:101802775469:repository/panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "execute-api:Invoke",
#      "Resource": "arn:aws:execute-api:us-east-1:101802775469:*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "iam:*",
#      "Resource": "arn:aws:iam::101802775469:role/panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "kms:*",
#      "Resource": [
#        "arn:aws:kms:us-east-1:101802775469:alias/panther-*",
#        "arn:aws:kms:us-east-1:101802775469:key/*"
#      ]
#    },
#    {
#      "Effect": "Allow",
#      "Action": "lambda:*",
#      "Resource": [
#        "arn:aws:lambda:us-east-1:101802775469:event-source-mapping:*",
#        "arn:aws:lambda:us-east-1:101802775469:function:panther-*",
#        "arn:aws:lambda:us-east-1:101802775469:layer:panther-*"
#      ]
#    },
#    {
#      "Effect": "Allow",
#      "Action": "s3:*",
#      "Resource": "arn:aws:s3:::panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "sns:*",
#      "Resource": "arn:aws:sns:us-east-1:101802775469:panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": "sqs:*",
#      "Resource": "arn:aws:sqs:us-east-1:101802775469:panther-*"
#    },
#    {
#      "Effect": "Allow",
#      "Action": [
#        "acm:*",
#        "apigateway:*",
#        "appsync:*",
#        "athena:*",
#        "cloudformation:List*",
#        "cloudwatch:*",
#        "cognito-idp:*",
#        "dynamodb:List*",
#        "ecr:GetAuthorizationToken",
#        "ecs:*",
#        "events:*",
#        "glue:*",
#        "kms:CreateKey",
#        "kms:List*",
#        "lambda:*EventSourceMapping",
#        "lambda:List*",
#        "logs:*",
#        "sns:List*",
#        "sqs:List*"
#      ],
#      "Resource": "*"
#    }
#    ]
#  }