// Code generated by apigen; DO NOT EDIT.
package logtypesclient

import (
	"context"
	lambdaclient "github.com/panther-labs/panther/pkg/x/apigen/lambdaclient"
)

// Models

type LambdaEventPayload struct {
	ListAvailableLogTypes *struct{}
}

type ListAvailableLogTypesOutput struct {
	LogTypes string `json:"logTypes"`
}

// Lambda client

type LambdaClient struct {
	client lambdaclient.Client
}

func NewLambdaClient(client lambdaclient.Client) *LambdaClient {
	if client.Validate == nil {
		client.Validate = func(interface{}) error { return nil }
	}
	return &LambdaClient{
		client: client,
	}
}

func (c *LambdaClient) ListAvailableLogTypes(ctx context.Context) (*ListAvailableLogTypesOutput, error) {
	lambdaEvent := LambdaEventPayload{
		ListAvailableLogTypes: &struct{}{},
	}
	output := ListAvailableLogTypesOutput{}
	if err := c.client.InvokeWithContext(ctx, &lambdaEvent, &output); err != nil {
		return nil, err
	}
	return &output, nil
}
