# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Compliance alert SQS queue and processing functions

Parameters:
  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period
    Default: 365
  Debug:
    Type: String
    Description: Toggle debug logging
    Default: false
    AllowedValues: [true, false]
  LayerVersionArns:
    Type: CommaDelimitedList
    Description: List of base LayerVersion ARNs to attach to every Lambda function
    Default: ''
  TracingMode:
    Type: String
    Description: Enable XRay tracing on Lambda and API Gateway
    AllowedValues: ['', Active, PassThrough]
    Default: ''

  AnalysisApiId:
    Type: String
    Description: API Gateway for analysis-api
  ComplianceApiId:
    Type: String
    Description: API Gateway for compliance-api
  RemediationApiId:
    Type: String
    Description: API Gateway for remediation-api
  SQSKeyId:
    Type: String
    Description: KMS key ID for SQS encryption

Conditions:
  AttachLayers: !Not [!Equals [!Join ['', !Ref LayerVersionArns], '']]
  TracingEnabled: !Not [!Equals ['', !Ref TracingMode]]

Resources:
  ##### Alert Processor #####
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-alert-processor-queue
      # <cfndoc>
      # This sqs queue contains events that may become alerts.
      # The `panther-alert-processor` lambda reads from this queue to
      # determine if the event requires action or is a duplicate.
      #
      # Failure Impact
      # * Failure of this sqs queue will impact delivery of alerts to output destinations.
      # * Failed events will go into the `panther-alert-processor-queue-dlq`. When the system has recovered they should be re-queued to the `panther-alert-processor-queue` using the Panther tool `requeue`.
      # </cfndoc>
      MessageRetentionPeriod: 1209600 # Max duration - 14 days
      KmsMasterKeyId: !Ref SQSKeyId
      VisibilityTimeout: 60 # Should match lambda timeout
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt [DeadLetterQueue, Arn]
        maxReceiveCount: 10

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: panther-alert-processor-queue-dlq
      # <cfndoc>
      # This is the dead letter queue for the `panther-alert-processor-queue`.
      # Items are in this queue due to a failure of the `panther-alert-processor` lambda.
      # When the system has recovered they should be re-queued to the `panther-alert-processor-queue` using
      # the Panther tool `requeue`.
      # </cfndoc>
      MessageRetentionPeriod: 1209600 # Max duration - 14 days
      VisibilityTimeout: 60

  AlertProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-alert-processor
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  AlertProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/compliance/alert_processor/main
      Description: Processes the events generated from the compliance engine
      Environment:
        Variables:
          DEBUG: !Ref Debug
          REMEDIATION_SERVICE_HOST: !Sub '${RemediationApiId}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
          REMEDIATION_SERVICE_PATH: v1
          COMPLIANCE_SERVICE_HOST: !Sub '${ComplianceApiId}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
          COMPLIANCE_SERVICE_PATH: v1
          POLICY_SERVICE_HOST: !Sub '${AnalysisApiId}.execute-api.${AWS::Region}.${AWS::URLSuffix}'
          POLICY_SERVICE_PATH: v1
          TABLE_NAME: !Ref Table
      Events:
        Queue:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
            BatchSize: 1
      FunctionName: panther-alert-processor
      # <cfndoc>
      # This lambda reads events from the `panther-alert-processor-queue`
      # generated by the `panther-policy-engine` lambda.  It updates the `panther-alert-forwarder` ddb table
      # (which enables deduplication) and may trigger remediation by calling the `panther-remediation-api`.
      #
      # Failure Impact
      # * Failure of this lambda will impact alerts generated policy violations.
      # * Failed events will go into the `panther-alert-processor-queue-dlq`. When the system has recovered they should be re-queued to the `panther-alert-processor-queue` using the Panther tool `requeue`.
      # </cfndoc>
      Handler: main
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      MemorySize: 128
      Runtime: go1.x
      Timeout: 60
      Tracing: !If [TracingEnabled, !Ref TracingMode, !Ref 'AWS::NoValue']
      Policies:
        - Id: ReadFromSQS
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt Queue.Arn
            - Effect: Allow
              Action: kms:Decrypt
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
        - Id: UpdateTable
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:UpdateItem
              Resource: !GetAtt Table.Arn
        - Id: InvokeGatewayApi
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: execute-api:Invoke
              Resource:
                - !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${RemediationApiId}/v1/POST/remediateasync
                - !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${ComplianceApiId}/v1/GET/status
                - !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${AnalysisApiId}/v1/GET/policy

  ##### Alert Forwarder #####
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: panther-alert-forwarder
      # <cfndoc>
      # The `panther-alert-forwarder` ddb table is updated conditionally when new policies have a violation
      # or a time limit has been exceeded.
      #
      # Failure Impact
      # * Processing of alerts could be slowed or stopped if there are errors/throttles.
      # </cfndoc>
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      PointInTimeRecoverySpecification: # Create periodic table backups
        PointInTimeRecoveryEnabled: True
      SSESpecification: # Enable server-side encryption
        SSEEnabled: True
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  AlertForwarderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/panther-alert-forwarder
      RetentionInDays: !Ref CloudWatchLogRetentionDays

  AlertForwarder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../out/bin/internal/compliance/alert_forwarder/main
      Description: Forwards the alerts to the alert delivery mechanism
      Environment:
        Variables:
          ALERTING_QUEUE_URL: !Sub https://sqs.${AWS::Region}.${AWS::URLSuffix}/${AWS::AccountId}/panther-alerts-queue
          DEBUG: !Ref Debug
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
      FunctionName: panther-alert-forwarder
      # <cfndoc>
      # The `panther-alert-forwarder` lambda reads from the ddb stream for the table `panther-alert-forwarder`
      # and sends them to the `panther-alerts-queue` sqs queue.
      #
      # Failure Impact
      # * Failure of this lambda will stop delivery of alerts to destinations.
      # * There will be no data loss until events are purged from the ddb stream (24 hours).
      # </cfndoc>
      Handler: main
      MemorySize: 128
      Runtime: go1.x
      Layers: !If [AttachLayers, !Ref LayerVersionArns, !Ref 'AWS::NoValue']
      Timeout: 60
      Policies:
        - Id: ReadTableStreams
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeStream
                - dynamodb:GetRecords
                - dynamodb:GetShardIterator
                - dynamodb:ListStreams
              Resource: !Sub ${Table.Arn}/stream/*
        - Id: PublishToAlertQueue
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:SendMessageBatch
              Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:panther-alerts-queue
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Sub arn:${AWS::Partition}:kms:${AWS::Region}:${AWS::AccountId}:key/${SQSKeyId}
