# Panther is a scalable, powerful, cloud-native SIEM written in Golang/React.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: Cognito User Pool

Parameters:
  PantherHost:
    Type: String
    Description: Load balancer URL hosting the deployed Panther website

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
        InviteMessageTemplate:
          EmailSubject: Welcome to Panther!
          EmailMessage: !Sub |
            <br />Welcome to Panther! We're very excited to have you on board!
            <br />
            <br />To get started, sign in to your <a href="https://${PantherHost}/sign-in">Panther dashboard</a> with the following temporary credentials:
            <br />
            <br />* Username: {username}
            <br />* Password: {####}
            <br />
            <br />Need help, or have questions? Just email us at support@runpanther.io, we'd love to help.
            <br />
            <br />Yours truly,
            <br />Panther - https://runpanther.io
            <br />
            <br /><small>Copyright © 2020 Panther Labs Inc. All rights reserved.</small>
      AutoVerifiedAttributes: # Attributes you want the user to verify (poor naming choice by AWS)
        - email
      LambdaConfig:
        CustomMessage: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:panther-cognito-custom-message-trigger
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: email
          Required: true
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: given_name
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: family_name
      UsernameAttributes:
        - email
      UserPoolName: panther-users

  AppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: Panther
      GenerateSecret: false
      RefreshTokenValidity: 1
      UserPoolId: !Ref UserPool
      WriteAttributes:
        - email
        - given_name
        - family_name

Outputs:
  UserPoolId:
    Description: Cognito user pool ID
    Value: !Ref UserPool
  AppClientId:
    Description: Cognito user pool client ID
    Value: !Ref AppClient
