name: 'Code Analysis'

on:
  pull_request:
    branches:
      - master
  schedule:
    # Run every Sunday at 3pm
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#schedule
    - cron: '0 15 * * 0'

jobs:
  code_analysis:
    name: Scan code for vulnerabilities
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'go', 'python']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event (and not a scheduled run), then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
